language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - MODULE_DIR=SlackLogger

install:
  - pip install .
  - pip install --upgrade pylint

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pylint --errors-only $MODULE_DIR

after_success:
  - python setup.py sdist bdist_wheel

jobs:
  include:
    - stage: deploy
      script: skip
      python: 2.7
      deploy:
        provider: pypi
        user: Greums
        password:
          secure: MqmE9eF6JAKjLscsM9uloPHozB3qmtJJcjFfHWm6DhmHJ0kAIZfnVpAEWUys0jXD1Y+n1TewJjsL1Y5suFlENx83mHxQuCAQm2X6cPWiKASrOablwkrw6qWQgRFUrJW1NSlFQEG6oLSHfdAQljIhQw7gi7AfkHoFbiwcC5eVMTUtjhuR1xKRms9dLMYHvMQpDKtNwxGbDmusdk2UODETpaSN05tHwe9+GnJaE7sOD53ecpNl++PRsHjTGIqvXv2wQcvlBnSTQ4LNpAyCmINOvYPQrjcPPCGjXWyPegj61YNYGiY1OSmUCnKfgfzBptZmzOJ37NUtYAEntGhh3VTbczXK7NWQ1cpYkHS+s2kgKgzyR3ihBT2guN53wUoJIKS/YhpeZz7YlaZ4re0zTPkpt5Clej9TOPghp3h7D2NcFK4IalD2prcajWP9OYLDYq/k0aaIDKwptGinFe1/PAvH+PgWOAOg4JuLk+Ks4D5UT7B/tM8EfY5NsANwKJE+HHemySmlEqDTIkgUG0YuKBKKK2ZOvs4Tu/CakFXoWzCSZv/9TavR4d/G9aqp6qOyaxmHjT/whdpnvId4ndXy103BcaFOHv53lk1mYc3fO3DbKYwC4gBjgYPd+GGjaYBBWm9LsQxELLZcZVTH0sieKFcVlELj/Z/9ZkFjzmhme5xKBAk=
        on:
          tags: true
          branch: master
        distributions: sdist bdist_wheel
      skip_cleanup: true

notifications:
  slack:
    secure: KYm6oAFn5bblkbpZ3Q5u66PWCmoof8UNHkNx8uI0owgJ2mnTq5L9YVW130tjia/MOqryCENMGlURC8F6v5wzNSr2A5hEBwGnrDL8aZIN82wvaQT130HDFbg0H8br3s6pV+eRRbyvkAhoEnTNegcWbwlLlEUTYKKMeLlfh3fICZ6Ul9uaINSjfk2qbStGkqnVcs+t43fK8UxrTQmJCSbrHOLdFNlyH0vFjEaK8qf7+LYa+kT041+KYB1ZxtOz/5pnpH/dLih24PUK/wlr0yrkbjbhWp/vTHXUb4LfewifyDULiw9AlsfsIPi2jgsNGn+Jz/zc53WN/tgkV/0uJCoWgmpt/u1IM+Y+JwHDNPqo/BHO4odw9H9ZpayvOfj8ZljbDiqn/06O+sT32MVRrnApGfQu1oWDRMyQGvzMSLM6zyX9Xs4CcdXovdCA5hBzfRrXoc40VMyxaqAw9PZy9TRWKl+FM5tdABcIKZN4qcujfvP3cOTdL6C3KrKely7nwougKYne5OgaGCbu1MGwL5wu3px4p6R7O/bt/6vHZ5HiXStG5sohiQ+LgeAQP7x7IWBaRNaePljgk/DMErHAZMVPFOKKPcrK577FBsjTJwUvG3so6gB9ahRhceDo8yk7c8N4yjB/GQEkHlBTIZ/trYUJceNsYFxwy37R58/IdMPIiyo=
