language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - MODULE_DIR=SlackLogger

install:
  - pip install .
  - pip install --upgrade pylint

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pylint --errors-only $MODULE_DIR

after_success:
  - python setup.py sdist bdist_wheel

jobs:
  include:
    - stage: deploy
      script: skip
      python: 2.7
      deploy:
        provider: pypi
        user: Greums
        password:
          secure: MqmE9eF6JAKjLscsM9uloPHozB3qmtJJcjFfHWm6DhmHJ0kAIZfnVpAEWUys0jXD1Y+n1TewJjsL1Y5suFlENx83mHxQuCAQm2X6cPWiKASrOablwkrw6qWQgRFUrJW1NSlFQEG6oLSHfdAQljIhQw7gi7AfkHoFbiwcC5eVMTUtjhuR1xKRms9dLMYHvMQpDKtNwxGbDmusdk2UODETpaSN05tHwe9+GnJaE7sOD53ecpNl++PRsHjTGIqvXv2wQcvlBnSTQ4LNpAyCmINOvYPQrjcPPCGjXWyPegj61YNYGiY1OSmUCnKfgfzBptZmzOJ37NUtYAEntGhh3VTbczXK7NWQ1cpYkHS+s2kgKgzyR3ihBT2guN53wUoJIKS/YhpeZz7YlaZ4re0zTPkpt5Clej9TOPghp3h7D2NcFK4IalD2prcajWP9OYLDYq/k0aaIDKwptGinFe1/PAvH+PgWOAOg4JuLk+Ks4D5UT7B/tM8EfY5NsANwKJE+HHemySmlEqDTIkgUG0YuKBKKK2ZOvs4Tu/CakFXoWzCSZv/9TavR4d/G9aqp6qOyaxmHjT/whdpnvId4ndXy103BcaFOHv53lk1mYc3fO3DbKYwC4gBjgYPd+GGjaYBBWm9LsQxELLZcZVTH0sieKFcVlELj/Z/9ZkFjzmhme5xKBAk=
        on:
          tags: true
          branch: master
        distributions: sdist bdist_wheel
      skip_cleanup: true

notifications:
  slack:
    secure: Gi5yhsidDzG2hFAwHTmiDqv6xwi55Dc4C00RHqkFg291t0KkSgvtCcEwehozGxzCeWgLDBIR3oi00OM0RQsz6iOfACJwocWVmoh8MGrhXz6g26d6OFAfSVHdPdtMS3TmuqqrdONuE4nEXQkYcB7OOAZPKNPe5ezyodj3zPswHqBnfFC3tRRYdPVNY4tAUvMG9KBClA3wnU1j2XqSd5mc/653mjiZxWc2k98xdaKWlmUtWvviiziVPukaJMoUqputsgTe0xeX3yXCYA5xBe6E+0bGMXSIBQou7Eec4zp+kMmkgzsybqj4rVAqXhwAdrowd7OvoiT3BWu8dHliWFFAl3tOw59E4C/E4r39TQ814LCwA+hbIIMzSUpUewyXnZD/D+O0nTvWR6WwJ2gvzuuwkX6064WXhEDERR/YBgaK0nzZpSP+Fo5FANlmQi8nrxFDZ0nsKwmGt7MVWQoFD8AR1kkV8wo9NSYH01MwqUonXdM1tZKgZLr5WOF6lricA/ktIsuoQMwg4U8VvDfhXs9hTJCS6gHeGtU4iMAMzJ6HZbGsvU60kkrJZQVdnZ0EezOvZFl9Upzc/ix9oWh4f/5ddUolaeeYZI70GquBWDiI6q9LBFmB0XpAvgPQwNS/+OdmvY8ZId3c4cjhjU/FyjEMTfK9uCzTAzh7qrovxTwxuCY=
